### ISSUE TITLE
英文系统下奇数页眉显示错误

### ISSUE THREAD

**Issue by Wangmz-1211** [TomPan-1901/SEUThesis-Word#1]
代码里写死的“标题 1” 改成“Heading 1”之后在英文系统下才能正常显示，不知道可否写成两种语言都能正常显示的？

**Comment by TomPan-1901** [comment]
Hi，Word对“标题1”-“标题9”样式做了特殊处理，在不同语言的Office中显示的名称不同，所以会出现上面的问题。
这个模板是用来写中文论文的，我没有打算修改这些标题的想法，如果您确实需要，可以自行修改模板：尝试基于标题1-9新建样式，并且在所有地方都应用新建的这些样式，自定义的样式名不会改变。
